services:
  api:
    build:
      context: .
      dockerfile: XY.ApiService/Dockerfile
    container_name: xy-api
    ports:
      - "5001:8080"
    environment:
      - ConnectionStrings__DefaultConnection=${DB_CONNECTION_STRING:-Server=localhost;Database=xy;User=sa;Password=YourStrong@Password;TrustServerCertificate=True}
      - REDIS_CONNECTION=${REDIS_CONNECTION:-localhost:6379}
    restart: always
    networks:
      - xy-network

  web:
    build:
      context: .
      dockerfile: XY.Web/Dockerfile
    container_name: xy-web
    ports:
      - "6789:8080"
    environment:
      - ApiService__Url=${API_SERVICE_URL:-http://api}
      - ApiService__Port=${API_SERVICE_PORT:-8080}
    depends_on:
      - api
    restart: always
    networks:
      - xy-network

networks:
  xy-network:
    driver: bridge
